name: Deploy to EC2 via ECR

// ... existing code ...

  # === STAGE 2: Run Tests ===
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: codeql-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Create Backend Test Environment File
        working-directory: ./backend
        run: |
          echo "DB_HOST=${{ env.DB_HOST }}" > .env.test
          echo "DB_USER=${{ env.DB_USER }}" >> .env.test
          echo "DB_PASSWORD=${{ env.DB_PASSWORD }}" >> .env.test
          echo "DB_NAME=${{ env.DB_NAME }}" >> .env.test

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false

// ... existing code ...
